from enum import Enum


class CountryCodes(Enum):
    united_states = "US"
    china = "CN"
    japan = "JP"
    germany = "DE"
    india = "IN"
    united_kingdom = "GB"
    france = "FR"
    italy = "IT"
    canada = "CA"
    south_korea = "KR"
    russia = "RU"
    brazil = "BR"
    australia = "AU"
    spain = "ES"
    mexico = "MX"
    indonesia = "ID"
    netherlands = "NL"
    switzerland = "CH"
    sweden = "SE"
    belgium = "BE"
    austria = "AT"
    argentina = "AR"
    norway = "NO"
    czech_republic = "CZ"
